### ISSUE TITLE
Is there a way to make the font size larger for the node names?

### ISSUE THREAD

**Issue by Peter-Barrett** [David-Desmaisons/Vue.D3.tree#25]
I'm looking to make the font size larger as it's quite small at the moment but couldn't see an option for it.

**Comment by David-Desmaisons** [comment]
```CSS
.treeclass .nodetree text {
  font: 10px sans-serif;
  cursor: pointer;
}
```

This is the CSS selector that gives the font size, if you create a more specific one (for example creatind the component inside a div with an id and using a #id .treeclass .nodetree text rule, you can alter font-size.
