### ISSUE TITLE
Question: How can I edit the style on the tree component?

### ISSUE THREAD

**Issue by beyondnetPeru** [David-Desmaisons/Vue.D3.tree#36]
Hi

Exists any form that we can edit styles on the tree component. For instance, I would like to change the color of each node, font size, line colors, etc.

Do you have any recommendation?

**Comment by darmen** [comment]
Hi @beyondnetPeru. You can do it using CSS:

```css
.treeclass .nodetree text {
    font-family: ...
    font-size: ...
}

.treeclass .nodetree circle {
    fill: ...
}

.treeclass .linktree {
    stroke: ...
    stroke-width: ...
}
```
