### ISSUE TITLE
Adding text size prop

### ISSUE THREAD

**Issue by covert8** [David-Desmaisons/Vue.D3.tree#60]
Hi, i'm trying to add a prop to influence `.treeclass .nodetree text`

The way i'm trying to do this is via a computed value and prop. But I can't find where the HTML is defined to add the v-bind:style. Where would I find the template or how would you go about this?

**Comment by guog** [comment]
use css,

scss
```scss
.tree {
  & ::v-deep {
    text {
      font-family: 'Roboto', 'Helvetica Neue', 'Helvetica', 'PingFang SC',
        'Hiragino Sans GB', 'Microsoft YaHei',Arial, sans-serif !important;
      font-size: 12px;
    }
  }
}
```
